bot:
    prefix:    "!"
    token:     !ENV "BOT_TOKEN"

markov:
    rebuild_hour: 0

# List of enabled cogs (groups of commands)
cogs:
    cogs:
        - hello
        - general
        - rankaisumetodit
        - dota
        - misc_games
        - ghost
        - misc
        - roller
        - stock
        - markov
        - random_msg
        - poe
        - release
        - f1
        - notify
